# Generated by Django 5.2.15 on 2026-07-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Override',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promise_id', models.IntegerField(unique=True)),
                ('human_decision', models.CharField(choices=[('kept', 'Kept'), ('broken', 'Broken'), ('open', 'Open')], max_length=10)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
